[package]
name = "rytest-collector-plugin"
description = "A pytest collection plugin from rytest"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[lib]
name = "rytest"
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
pyo3 = { version = "0.22.6", features = ["extension-module"] }
walkdir = "2.5.0"
